server:
  port: 7911
  display-name:  user-thrift-service
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@192.168.0.11:1521:DB_USER
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: xhz
    password: root